language: java
jdk: oraclejdk7
env:
  matrix:
    # android-19 is always included
    - ANDROID_SDKS=sysimg-19            ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  # changed install to -q instead of -qq to expose any missing packages
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -q --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar xzf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Maven 3.1.1
  - wget http://www.us.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
  - tar xvf apache-maven-3.1.1-bin.tar.gz > /dev/null
  - export MVN_HOME=`pwd`/apache-maven-3.1.1
  - export PATH=${MVN_HOME}/bin/:${PATH}
  - mvn --version

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  # Note that sysimg-19 downloads the ARM, x86 and MIPS images (we should optimize this).
  # Other relevant API's:
  #  addon-google_apis-google-16
  # removed > /dev/null to prevent Travis timing out and ease debugging
  - echo y | android update sdk --filter tools,platform-tools --no-ui --force --all
  - echo y | android update sdk --filter build-tools-19.0.3 --no-ui --force --all
  - echo y | android update sdk --filter $ANDROID_TARGET --no-ui --force --all
  - echo y | android update sdk --filter $ANDROID_SDKS --no-ui --force --all

  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script: mvn clean install -Dandroid.device=test

after_script:
  # Install Android NDK
  - NDK_ARCH=""
  - if [ `uname -m` = x86_64 ]; then NDK_ARCH=_64; fi
  - wget http://dl.google.com/android/ndk/android-ndk-r8e-linux-x86${NDK_ARCH}.tar.bz2
  - tar xjf android-ndk-r8e-linux-x86${NDK_ARCH}.tar.bz2
  - export ANDROID_NDK_HOME=$PWD/android-ndk-r8e

  # Run the samples.
  - mkdir target
  - git clone git://github.com/jayway/maven-android-plugin-samples.git target/maven-android-plugin-samples
  - mvn android:undeploy clean install -B -f target/maven-android-plugin-samples/pom.xml -Dandroid.device=test
